[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]
ffi = true # enables foundry to run commands on your local machine

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
